In [7]:
import torch
import torch.nn as nn
mat_a = torch.randn(size=(2,3,4))
mat_b = nn.Softmax(dim=-1)(mat_a)

print(mat_a)
print(mat_b)


tensor([[[-2.4547,  0.4984,  1.6643, -0.4151],
         [-0.9940,  0.1728, -0.1262, -0.1817],
         [-0.6015, -0.2139, -0.6691,  0.5880]],

        [[ 0.9981, -0.9248,  0.6317, -1.0752],
         [-1.2651,  0.3356, -1.8668, -0.9512],
         [-0.4375, -0.2201,  0.0886,  0.7578]]])
tensor([[[0.0112, 0.2145, 0.6883, 0.0860],
         [0.1130, 0.3631, 0.2692, 0.2547],
         [0.1494, 0.2201, 0.1396, 0.4908]],

        [[0.5089, 0.0744, 0.3528, 0.0640],
         [0.1270, 0.6295, 0.0696, 0.1739],
         [0.1381, 0.1717, 0.2338, 0.4565]]])


In [8]:
matc = torch.ones(size=(3,3))
matd = torch.ones(1)
matx = 2*torch.ones(1)

mattest = matx*matc + matd

print(matc)
print(matd)
print(mattest)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([1.])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])


In [10]:
print(1e-5)
print(type(1e-5))

1e-05
<class 'float'>


In [2]:
import torch
testa = torch.ones(10)
print(testa)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
